language: java

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - izeye@naver.com
    on_success: always
    on_failure: always

after_success:
  - ./gradlew jacocoTestReport coveralls